image: docker:latest

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ''

services:
  - docker:dind

stages:
  - build
  # - deploy

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# build stage

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/api .
    - docker push $CI_REGISTRY_IMAGE/api
  only:
    - master
